# Generated by Django 5.0.6 on 2024-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=150)),
                ('Clicks', models.CharField(max_length=100)),
                ('Impressions', models.CharField(max_length=100)),
                ('Ranking', models.CharField(max_length=100)),
                ('CTR', models.CharField(max_length=100)),
            ],
        ),
    ]
