# Generated by Django 5.0.6 on 2024-06-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_date_delete_dates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='date',
            table='date_model',
        ),
    ]
