# Generated by Django 5.0.6 on 2024-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_date_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADFResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('adf_statistic', models.FloatField()),
                ('p_value', models.FloatField()),
                ('critical_value_1', models.FloatField()),
                ('critical_value_5', models.FloatField()),
                ('critical_value_10', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
