# Generated by Django 5.0.6 on 2024-07-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_adfresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfresult',
            name='stationery_test',
            field=models.FloatField(null=True),
        ),
    ]
