# Generated by Django 5.0.6 on 2024-07-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_adfresult_stationery_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfresult',
            name='stationery_test',
        ),
    ]
