# Generated by Django 5.2 on 2025-05-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADFResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('adf_statistic', models.FloatField()),
                ('p_value', models.FloatField()),
                ('critical_value_1', models.FloatField()),
                ('critical_value_5', models.FloatField()),
                ('critical_value_10', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=150)),
                ('Clicks', models.CharField(max_length=100)),
                ('Impressions', models.CharField(max_length=100)),
                ('Ranking', models.CharField(max_length=100)),
                ('CTR', models.CharField(max_length=100)),
                ('Release_Date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'date_model',
            },
        ),
    ]
